export const keywordGroups = [
    // {
    //     title: "🔍 Bệnh lý tổng quát",
    //     items: ["nhập viện", "điều trị", "khám bệnh", "bệnh sử", "chẩn đoán"],
    // },
    {
        title: "🫁 Triệu chứng hô hấp & phổi",
        items: [
            "ho",
            "ho đàm",
            "ho khan",
            "ho ra máu",
            "khò khè",
            "khó thở",
            "thở gấp",
            "cơ kéo cơ hô hấp",
            "đau tăng khi hít sâu",
            "ran nổ",
            "ran rít",
            "ran ẩm",
            "rale nổ",
            "phổi ran",
            "phổi thô",
            "phổi rale",
            "phổi ít ran",
            "co lõm ngực",
            "giảm âm",
            "đàm trắng",
            "khạc đàm"
        ],
    },
    {
        title: "❤️ Tim mạch - Tuần hoàn",
        items: [
            "tim đều",
            "tim đều rõ",
            "mạch rõ",
            "mạch quay rõ",
            "huyết áp cao",
            "huyết áp thấp",
            "tăng huyết áp",
            "chi ấm",
            "chi ấm mạch rõ",

        ],
    },
    {
        title: "🌡️ Triệu chứng toàn thân",
        items: [
            "sốt",
            "sốt cao",
            "ớn lạnh",
            "chán ăn",
            "buồn nôn",
            "nôn",
            "ói",
            "suy kiệt",
            "mệt mỏi",
            "ăn uống kém",
            "tổng trạng gầy",
            "nhiệt độ 37 độ",
            "đau toàn thân",
            "mất sức",
            "tiêu chảy",
            "tiểu buốt",
            "đau thượng vị",
        ],
    },
    {
        title: "🩺 Khám lâm sàng - Da niêm - Cảm giác tiếp xúc",
        items: [
            "bệnh tỉnh",
            "niêm hồng",
            "da niêm hồng",
            "chi ấm mạch rõ",
            "tiếp xúc tốt",
            "môi hồng",
            "tím môi",
            "hồng nhạt",
            "tím tái",
            "niêm hồng nhạt",
            "da niêm",
            "da xanh tái",
            "sờ không chạm",
        ],
    },
    {
        title: "🧍 Cơ quan nội tạng & vùng khám",
        items: [
            "bụng mềm",
            "gan lách",
            "gan lách sờ không chạm",
            "đau thượng vị",
            "đau bụng",
            "đau gan",
            "lách to",
            "tiêu chảy",
            "tiêu lỏng",
            "tiểu nhiều",
            "suy thận"
        ],
    },
    {
        title: "🧠 Thần kinh - Ý thức - Hành vi",
        items: [
            "tỉnh",
            "lơ mơ",
            "mê",
            "không đáp ứng",
            "chóng mặt",
            "yếu liệt",
            "suy nhược",
        ],
    },
    {
        title: "🦴 Cơ xương khớp - Cảm giác",
        items: [
            "đau lưng",
            "đau ngực",
            "đau cơ",
            "mỏi",
            "đau lói",
            "cứng cơ",
            "co giật"
        ],
    },
    {
        title: "🧾 Tiền sử bệnh",
        items: [
            "lao",
            "hen phế quản",
            "suy hô hấp",
            "phù phổi",
            "tràn dịch màng phổi",
            "tràn khí màng phổi",
            "u phổi",
            "viêm phổi",
            "xẹp phổi",
            "tim",
            "lao phổi",
            "covid",
            "viêm dạ dày",
            "viêm ruột",
            "viêm ruột thừa",
            "tăng huyết áp",
            "đái tháo đường",
            "copv",
            "sỏi túi mật",
            "nhồi máu cơ tim",
            "tai biến",
            "tai biến mạch máu",
            "suy thận mạn",
            "suy tim",
            "xuất huyết",
            "bệnh lý tim mạch",
            "bệnh phổi mạn tính"
        ],
    }
];
